import type { Curriculum } from "@engineering-playbook/content-schema";

export const curriculum: Curriculum = {
  areaOrder: ["backend-systems"],

  categoriesInArea: {
    "backend-systems": [
      "practical-data-structures",
      "distributed-systems",
      "messaging",
      "caching",
      "design-patterns",
    ],
  },

  topicsInCategory: {
    "practical-data-structures": [
      "bloom-filter",
      "lru-cache",
      "consistent-hashing",
      "trie",
      "skip-list",
      "heap-priority-queue",
      "bitmaps-bitsets",
      "hyperloglog",
      "count-min-sketch",
      "merkle-tree",
    ],
    "distributed-systems": [
      "consistent-hashing",
      "leader-election",
      "replication",
      "sharding",
      "quorum",
      "gossip-protocol",
      "heartbeats",
      "circuit-breaker",
      "retry-exponential-backoff",
      "idempotency",
      "distributed-lock",
      "lease",
      "saga-pattern",
      "outbox-pattern",
      "cqrs",
      "event-sourcing",
      "rate-limiter",
    ],
    messaging: [
      "pub-sub",
      "consumer-groups",
      "dead-letter-queue",
      "delivery-semantics",
      "deduplication",
      "ordering",
      "backpressure",
      "competing-consumers",
    ],
    caching: [
      "lru-cache",
      "cache-aside",
      "write-through",
      "write-behind",
      "read-through",
      "ttl",
      "cache-invalidation",
      "cache-stampede",
      "distributed-cache",
    ],
    "design-patterns": [
      "strategy",
      "factory",
      "adapter",
      "decorator",
      "observer",
      "command",
      "repository",
      "dependency-injection",
    ],
  },
};
