import type { LearningPath } from "@engineering-playbook/content-schema";

export const learningPaths: LearningPath[] = [
  {
    id: "backend-engineer",
    slug: "backend-engineer",
    title: "Backend Engineer",
    summary: "A broad tour of the data structures and patterns that come up daily in backend work.",
    audience: "Backend engineers",
    topicIds: [
      "bloom-filter",
      "lru-cache",
      "consistent-hashing",
      "rate-limiter",
      "idempotency",
      "circuit-breaker",
      "cache-aside",
      "pub-sub",
      "strategy",
      "repository",
    ],
  },
  {
    id: "distributed-systems",
    slug: "distributed-systems",
    title: "Distributed Systems",
    summary: "Coordination, consistency, and failure-handling patterns for multi-node systems.",
    audience: "Backend / infrastructure engineers",
    topicIds: [
      "consistent-hashing",
      "leader-election",
      "replication",
      "sharding",
      "quorum",
      "gossip-protocol",
      "heartbeats",
      "distributed-lock",
      "lease",
      "idempotency",
      "saga-pattern",
      "outbox-pattern",
      "cqrs",
      "event-sourcing",
    ],
  },
  {
    id: "messaging",
    slug: "messaging",
    title: "Messaging",
    summary:
      "Reliable, ordered, and scalable communication between services via queues and streams.",
    audience: "Backend engineers",
    topicIds: [
      "pub-sub",
      "consumer-groups",
      "dead-letter-queue",
      "delivery-semantics",
      "deduplication",
      "ordering",
      "backpressure",
      "competing-consumers",
    ],
  },
  {
    id: "caching",
    slug: "caching",
    title: "Caching",
    summary: "Strategies for keeping hot data close to where it's read, and keeping it correct.",
    audience: "Backend engineers",
    topicIds: [
      "lru-cache",
      "cache-aside",
      "write-through",
      "write-behind",
      "read-through",
      "ttl",
      "cache-invalidation",
      "cache-stampede",
      "distributed-cache",
    ],
  },
  {
    id: "probabilistic",
    slug: "probabilistic",
    title: "Probabilistic Data Structures",
    summary:
      "Trading exactness for massive space and time savings — filters, sketches, and cardinality estimators.",
    audience: "Backend / data engineers",
    topicIds: ["bloom-filter", "hyperloglog", "count-min-sketch", "bitmaps-bitsets"],
  },
  {
    id: "design-patterns",
    slug: "design-patterns",
    title: "Design Patterns",
    summary: "Classic object-oriented patterns that show up in backend codebases every day.",
    audience: "Software engineers",
    topicIds: [
      "strategy",
      "factory",
      "adapter",
      "decorator",
      "observer",
      "command",
      "repository",
      "dependency-injection",
    ],
  },
];
